---
title: Evidence for systemic age underestimation in shark and ray ageing studies
subtitle: | 
    | Systemic age underestimation of cartilaginous fishes
    | Effects of systemic age underestimation in cartilagnious fishes
author: |
    | Alastair Varley Harry
    | Centre for Sustainable Tropical Fisheries and Aquaculture & College of Science and Engineering, James Cook University, Townsville, QLD, 4811, Australia
    | alastair.harry@gmail.com
    | *Running title: Age underestimation in sharks and rays*
output: 
  pdf_document:
    keep_tex: true
linestretch: 2 
csl: "../references/fish-and-fisheries.csl"
bibliography: "../references/Age underestimation.bib"
header-includes:
    - \fontsize{12}{20}
    - \usepackage{lineno}
    - \linenumbers
    - \linenumberfont
    - \renewcommand\linenumberfont{\normalfont\small\sffamily}
    - \pagenumbering{gobble} 
---

```{r setup, include=FALSE}
source("../analysis/setup.R")
source("../analysis/data prep.R")
source("../analysis/summary.R")
```

\newpage
### Abstract
Numerous studies have now demonstrated that the most common method of ageing sharks and rays, counting growth zones on calcified structures, can underestimate true age. I reviewed bomb carbon dating (n=`r byMethod[1,2]`) and fluorochrome chemical marking (n=`r byMethod[2,2]`) age validation studies to investigate the frequency and magnitude of this phenomenon. Age was likely to have been underestimated in `r UnderestimateGenus%>%n2w` of `r levels(data1$Genus)%>%length` genera and `r (sum(Underestimate[,1])/ sum(Underestimate))%>% round(2)*100`% of the `r sum(Underestimate)` populations studied, including `r (Underestimate[1,1]/ sum(Underestimate[1,]))%>% round(2)*100`% of those validated using bomb carbon dating. Length and age were strongly significant predictors of occurrence, with age typically underestimated in larger and older individuals. These characteristics suggest age underestimation is likely a systemic issue associated with the current methods and structures used for ageing. Where detected using bomb carbon dating, growth zones were reliable up to `r round(MASS::dose.p(m1)[1],2)*100`% of asymptotic length ($L_\infty$) and `r round(MASS::dose.p(m2)[1],2)*100`% of maximum age ($A_{Max}$). The maximum magnitude of age underestimation, $\Delta_{Max}$, ranged from `r DeltaMaxRange[1]%>%n2w` to `r DeltaMaxRange[2]` years, averaging `r DeltaMaxMean` years across species. Current perceptions of shark and ray life histories are informed to a large extent by growth studies that assume calcified ageing structures are valid throughout life. The widespread age underestimation documented here shows this assumption is frequently violated, with potentially important consequences for conservation and management. In addition to leading to an underestimation of longevity, the apparent loss of population age structure associated with it may unexpectedly bias growth and mortality parameters. Awareness of these biases is essential given shark and ray population assessments often rely exclusively on life history parameters derived from ageing studies. 

Keywords: age validation; bomb carbon dating; chondrichthyes; fluorochrome marking; life history; longevity

\newpage
\tableofcontents


\newpage
## Introduction
The credibility of fish age estimates derived from counts of concentric growth zones on calcified structures relies on validating the temporal periodicity of formation over the lifespan of the species [@beamish_forgotten_1983; @campana_accuracy_2001]. This basic tenet underlies a substantial amount of modern fisheries science including any stock assessment that relies on ages derived from these methods, ranging from simple equilibrium methods such as catch curves or per-recruit analyses to integrated population dynamics models [@maunder_review_2013]. Age is also used in many qualitative risk-based methods [@patrick_using_2010; @hobday_ecological_2011] and measures of intrinsic vulnerability [@dulvy_methods_2004; @cortes_perspectives_2016], ultimately informing management strategies for sustainable exploitation and conservation.

In chondrichthyan fishes (hereafter "sharks and rays"), where ageing methodology developed at a much slower pace than teleosts, the first concerted efforts to determine age [@prince_proceedings_1983; @cailliet_elasmobranch_1986] coincided with a renewed focus on age validation across the wider discipline [@beamish_forgotten_1983]. The many reviews on shark and ray ageing have repeatedly emphasized the importance of validation to practitioners [@cailliet_elasmobranch_1986; @cailliet_elasmobranch_1990; @cailliet_age_2004; @cailliet_age_2006; @goldman_assessing_2012; @cailliet_perspectives_2015]. Accordingly, validation has become an integral and expected part of most studies, particularly when using the most common method of counting growth zones on thin sections of vertebrae or spines. 

Within the past two decades global ageing of shark and ray populations has increased rapidly, in parallel with attempts by governments to implement policies of fisheries management and biodiversity conservation to meet international commitments [@fischer_review_2012]. Operationalising these policies invariably requires the assessment of fishing impacts on populations. This has major implications for shark and ray species, of which an estimated one quarter are threatened by overfishing [@dulvy_extinction_2014]. In practice, it has meant more regular stock assessments on target species, and risk assessments on non-target components of the catch including bycatch and threatened species. With greater numbers and diversity of sharks and rays being aged to support these assessments, corresponding studies have successfully validated part or all of the lifespan in a growing number of species [@cailliet_perspectives_2015].

Yet the increasing attempts at validating growth zones have not always yielded successful or expected results. One issue that has become increasingly apparent is that of age underestimation, a phenomenon that appears to result from growth zones ceasing to form or becoming unresolvable or unreliable beyond a certain size or age. The first detailed account of age underestimation was in New Zealand porbeagle sharks (*Lamna nasus*, Lamnidae) [@francis_age_2007]. Using bomb radiocarbon dating,  levels of $\Delta^{14}\textup{C}$ radio isotopes were found to be 'phase-shifted' relative to reference chronologies. This implied that some sharks were more than twice as old as originally thought and that growth zones were only reliable in individuals up to 20 years old. Similar phase-shifts, which have also been termed 'missing time', have now been reported in several other species studied using bomb carbon dating, including for populations where well-established and even previously validated ageing protocols existed [@andrews_bomb_2011; @passerotti_maximum_2014]. 

Age underestimation is not only limited to bomb carbon dating and direct evidence has also been found using other age validation techniques such as chemical marking. This includes cases where recaptured individuals failed to deposit expected annual growth increments after several years at liberty [@chin_validated_2013; @harry_age_2013]. Further circumstantial evidence that growth zone counts underestimate true longevity is apparent from some long-term tagging studies, most strikingly in the school shark (*Galeorhinus galeus*, Triakidae) where tag recaptures of up to 42 years at liberty are more than double the highest age based on growth zone counts [@moulton_age_1992; @francis_age_2007]. 

The full extent of age underestimation in shark and ray ageing studies is unknown, and its implications have not been investigated. McPhie and Campana [-@mcphie_bomb_2009] suggest that improper age assignment due to age underestimation in skates could have potentially severe management implications. Chin *et al.* [-@chin_validated_2013] state that the underestimation of longevity would impact demographic analyses. Noting the increasing prevalence in long-lived species, Natanson *et al.* [-@natanson_validated_2014] questioned the value of vertebral ageing. Despite these concerns, the *a priori* assumption that annual growth zones form throughout life persists [@cailliet_age_2004; @francis_age_2007; @passerotti_maximum_2014]. In light of the mounting evidence for age underestimation there is a need to re-examine this assumption. 

To investigate this issue I reviewed two common approaches for age validation; chemical marking and bomb carbon dating. Fluorescent dyes such as oxytetracycline (OTC) and calcein have successfully been used to mark the calcified structures of tagged and recaptured or captive sharks and rays since the 1970s [@holden_age_1973]. The technique involves injecting a fluorescent marker into the muscle or body cavity of the fish that is then rapidly incorporated into calcified structures providing a permanent record of when the individual was caught [@izzo_incorporation_2007]. The use of bomb carbon dating is more recent, but has been applied to sharks and rays since the 2000s [@campana_bomb_2002]. This method involves comparing $\Delta^{14}\textup{C}$ radio isotope levels in growth zones of unknown age with known-age reference chronologies [@kalish_pre-and_1993]. The rapid increase in $\Delta^{14}\textup{C}$ in marine dissolved inorganic carbon that occurred globally as a result of nuclear testing during the late 1950s is preserved as a distinct signature in calcified tissues of organisms alive during this period, allowing age estimates to be corroborated. These methods were chosen as they are generally considered to be the most robust methods for validating periodicity of growth zone deposition in sharks and rays [@goldman_assessing_2012] and marine organisms more generally [@campana_accuracy_2001]. While the two techniques differ considerably in their applications and are subject to a range of assumptions [@campana_chemistry_1999], they are nonetheless the most likely to detect age underestimation.

In reviewing evidence for age underestimation I (1) quantify its frequency of detection, (2) quantify its magnitude and the lengths and ages at which it manifests, and (3) assess how pervasive it is likely to be in shark and ray ageing studies. Using the New Zealand porbeagle shark as an example, I formulate hypotheses about the potential impacts and management implications. I conclude  by discussing options for addressing the issue and the challenges of shark and ray age validation more generally. 

## Materials and methods
To determine the frequency of age underestimation, I conducted a comprehensive review of all bomb carbon dating and chemical marking studies. I primarily restricted my search to peer-reviewed primary literature, although some influential technical reports or books were also included. Prior to 2006 a series of literature reviews on age determination in sharks and rays provided an exhaustive list of validation studies [@cailliet_elasmobranch_1986; @cailliet_elasmobranch_1990; @cailliet_age_2004; @cailliet_age_2006]. Studies from 2006 onward were obtained through a search of online databases. Long-term studies that resulted in multiple publications were grouped e.g. Smith [-@smith_timing_1984], Kusher *et al.* [-@kusher_validated_1992], and Smith *et al.* [-@smith_age-validation_2003].

Evidence of age underestimation was clear and definitive in some cases, but subjective in others. Based on the strength of evidence, age underestimation was classified as either 'likely' or 'possible'. The latter category included cases where evidence was ambiguous, circumstantial in nature, or was retrospectively invoked as an explanation. For example, interpretation of $\Delta^{14}\textup{C}$ signatures used for bomb carbon dating can be confounded by multiple factors. As diet is the source of carbon in shark and ray vertebrae, $\Delta^{14}\textup{C}$ signatures are expected to be phase-shifted relative to reference chronologies because they feed upon prey with a  $^{14}\textup{C}$ content different to the surrounding water [@campana_bomb_2002]. Depth-related attenuation, interspecific variability, regional differences, ontogeny, and incorrect interpretation of growth zones may further affect $\Delta^{14}\textup{C}$ signatures [@campana_chemistry_1999; @goldman_assessing_2012; @andrews_validated_2015], making it necessary to formulate hypotheses about the potential cause of any observed phase-shift. 

Where age validation studies were accompanied by a full age and growth study, I also attempted to quantify the magnitude of age underestimation at the population level. Information was collected on the range of ages validated, the apparent longevity of the species (based on the highest growth zone counts), and the true longevity of the species (based on age validation). These data were used to classify the lifespan into three components; validated ages, uncertain ages, and underestimated ages (Table 1). The apparent proportion of the lifespan that growth increments were reliable for was calculated based on these classifications, assuming that the periodicity of growth zone deposition was the same for all ages (unless otherwise specified). Where only lengths of validated individuals were provided, the inverse of the corresponding growth function was used to determine the approximate range of ages validated. 

Most bomb carbon dating studies reported the details of all individuals studied. This allowed the lengths and ages in which age underestimation manifested to be investigated. In the subset of populations where it was detected, data on the length, sex, apparent age, and true age (Table 1) were collated for each individual studied. The mean and maximum difference between true and apparent age, $\Delta_{Mean}$ and $\Delta_{Max}$ respectively, were determined for each population. Age was divided against the oldest individual reported ($A_{Max}$), and length divided against asymptotic length ($L_\infty$) or, if unavailable, the largest individual reported, to provide two dimensionless indices of relative age and length. These indices were used to statistically investigate the incidence of age underestimation as a function of length and age. Incidence of age underestimation was modeled separately as a function of relative length and age using Generalized Linear Models of the form $$Y_i\sim Bernoulli(p_i)$$ $$p_i=logit^{-1}\left (\beta_1+\beta_2\cdot  x_i  \right )$$ where the probability, $Y_i$, that the age of sample *i* was underestimated, was approximated by a Bernoulli random variable, $x_i$ is relative length or relative age, $\beta_1$ and $\beta_2$ are parameters estimated using maximum likelihood, and $logit^{-1}(X)$ is the logistic function $exp(X)/(exp(X)+1)$. Data were insufficient to include other explanatory variables (e.g. species, sex) in the model structure. All analyses and graphics were undertaken using R [@r_core_team_r:_2016]. 

## Results and Discussion
Between `r min(data$Year)` and `r max(data$Year)` there were `r nstudy` unique studies including `r byMethod[2,2]` that used chemical marking and `r byMethod[1,2]` that used bomb carbon dating (a single study by Andrews *et al.* [-@andrews_bomb_2011] used both methods). In total `r nrow(data)` populations of chondrichthyans were studied of which `r nrow(data)-nrow(data1)`, all chemically marked, were excluded from further analysis because they either failed to validate any regular temporal periodicity in growth zones, were purely methodological, or did not provide any details of the lengths or ages validated. The final data analysed included `r rowSums(Underestimate)[1]` populations validated using bomb carbon dating and `r rowSums(Underestimate)[2]` using chemical marking (see Supplementary Material for complete reference list and data). 

The majority (`r ((100*taxon[1]/sum(taxon))%>%round(0))`%) of studies were conducted on sharks including `r bySpp$Shark` species from `r byGenus$Shark` genera and `r byOrder$Shark%>%n2w` orders, with ground sharks (Carcharhiniformes) and mackerel sharks (Lamniformes) studied most frequently. Studies on rays and skates consisted of `r bySpp$Ray%>%n2w` species from `r byGenus$Ray%>%n2w` genera and `r byOrder$Ray%>%n2w` orders. No studies were done on chimaeras. Vertebrae were the primary ageing structure validated, making up `r (100*sum(Structure[2,])/sum(Structure))%>%round(0)`% of studies, although a small number of studies on dogfish (Squaliformes) and horn sharks (Heterodontiformes) used spines. Most studies (`r (100*sum(Structure[,2])/ sum(Structure))%>%round(0)`%) counted growth zones in thin-sections of vertebrae or spines, with the remainder using whole or half structures for ageing.

### Frequency of detection
Across both validation methods there were `r sum(Underestimate[,-2])` populations identified where age underestimation was likely or possible (Table 2). Age underestimation was detected most frequently with bomb carbon dating where it was inferred from phase-shifted $\Delta^{14}\textup{C}$ signatures (Fig. 1). The first phase-shift attributed to age underestimation was documented in school sharks by Kalish and Johnston [-@kalish_determination_2001], however the phenomenon did not gain widespread exposure until its discovery in New Zealand porbeagle sharks [@francis_age_2007]. To date, phase-shifts in `r Underestimate[1,1]` populations have been directly attributed to age underestimation. Documented cases involved `r UnderSpecies[1,2]%>%n2w` species from `r UnderGenus[1,2]%>%n2w` genera (Table 2). In general, the large temporal shift in $\Delta^{14}\textup{C}$ signature ($\geq$ five years) led authors to conclude that age must have been underestimated, as phase-shifts of this magnitude are inconsistent with other possible explanations [@goldman_assessing_2012]. 

There were also several populations where unexplained, shorter, phase-shifts were observed. These were distinct from phase-shifts attributable to the metabolically-derived carbon present in ageing structures, which generally results in radiocarbon signatures lagging reference chronologies by a few years [@campana_bomb_2002]. Ontogenetic dietary and depth changes were invoked to explain the $\Delta^{14}\textup{C}$ values in a northwest Atlantic tiger shark (*Galeocerdo cuvier*, Carcharhinidae) that were phase-shifted relative to other individuals studied [@kneebone_using_2008]. The authors noted parallels with a study on northeast Pacific white sharks (*Carcharadon carcharias*, Lamnidae) [@kerr_investigations_2006], however the phase-shift in that study was later attributed to age underestimation [@andrews_validated_2015]. Methodological error was thought to explain phase-shifts in some samples of spiny dogfish (*Squalus* spp., Squalidae) [@campana_bomb_2006] and shortfin mako (*Isurus oxyrinchus*, Lamnidae) [@ardizzone_application_2006] --- the latter species is also further complicated by its potentially variable growth zone deposition [@natanson_validated_2006; @kinney_oxytetracycline_2016]. Although not considered in these cases, underestimation of age by a few years could conceivably be a causal factor. Excluding these studies where evidence was ambiguous, age underestimation still likely occurred in a minimum of `r (100*sum(Underestimate[1,-c(2,3)])/ sum(Underestimate[1,]))%>%round(1)`% of bomb carbon dating studies (Table 2). 

Fewer chemically marked populations exhibited signs of age underestimation; it occurred in `r sum(Underestimate[2,-2])%>%n2w` populations, including `r Underestimate[2,1]%>%n2w` considered to be likely and `r Underestimate[2,3]%>%n2w` possible (Fig. 2, Table 2). Likely cases involved `r UnderSpecies[2,2]%>%n2w` species from `r UnderGenus[2,2]%>%n2w` genera. They included several instances where chemical marks were visible on the distal margin of vertebrae of individual specimens following recapture after several years, indicating that no growth zones had been formed subsequently [@pierce_validated_2009; @chin_validated_2013; @harry_age_2013; @frazier_validated_2014]. Walker *et al.* [-@walker_age_2001] also provided population-level evidence of age underestimation in school sharks, a finding consistent with the bomb carbon dating by Kalish and Johnston [-@kalish_determination_2001]. Using analysis of variance, the mean number of annual growth zones was found to be significantly less than one in length classes >1000 mm, with sharks > 1400 mm producing, on average, one growth zone every four years. 

Age underestimation was possible in a further `r Underestimate[2,3]%>%n2w` chemically marked populations. Natanson [-@natanson_effect_1993] hypothesized that growth zone deposition may cease in reproductively active females based on a captive study of little skates (*Raja erinacea*, Rajidae). Davenport and Stevens [-@davenport_age_1988] aged Australian blacktip sharks (*Carcharhinus tilstoni*, Carcharhinidae) to 12 years old, using chemical marking and marginal increment techniques for validation. A subsequent recapture after 18 years (estimated to have been at least two when tagged) suggests substantially greater longevity [@harry_age_2013]. Similar long-term recaptures of school shark and bonnethead sharks (*Sphyrna tiburo*, Sphyrnidae) have also been reported [@francis_age_2007; @frazier_validated_2014]. The overall level of detection in chemical validation studies was lower than that of bomb carbon dating. Nonetheless it was likely to have occurred in at least `r (100*sum(Underestimate[2,-c(2,3)])/ sum(Underestimate[2,]))%>%round(0)`% of populations. 

The limitations on both methods for detecting age underestimation, and also the difficulty of comparing detection levels between them, are highlighted in Figures 1 and 2. Bomb carbon dating was typically done of a small number of the oldest and largest individuals sampled and the method validates the entire lifespan of those individuals (Fig. 1). As age underestimation is generally assumed to occur in older and larger individuals, it follows that this method is more likely to detect it. Except in a few cases, chemical marking typically only validated a small subset of the total lifespan of the population and did not include older individuals, which are presumably both less abundant and less amendable to tag and recapture due to their larger size (Fig. 2). As such, age underestimation may not be expected to be detected in as many chemical marking studies. 

At least two other factors may confound or limit the ability to detect age underestimation using these methods. The failure of fluorochrome dyes to actually mark the vertebrae of some individuals was noted in numerous chemical marking studies. For example, McFarlane and Beamish [-@mcfarlane_validation_1987] reported that OTC marks failed to form in 34% of Pacific spiny dogfish (*Squalus suckleyi*, Squalidae) spines, and that marking success rates varied between seasons. Walker *et al.* [-@walker_age_2001] attributed this type of failure to either a lack of vertebral mineralization due to low somatic growth rates or methodological error such as a failure to properly inject chemicals into the body cavity of the fish. Since age underestimation is also typically attributed to the slowing or cessation of growth, these outcomes may be confounded. If slow growth does indeed limit or stop the incorporation of chemical markers in calcified structures it implies that they would no longer be useful as a validation tool. The ability to detect a small underestimation of age using bomb carbon dating is also unclear since it would presumably be difficult to distinguish from phase-shifts related to the metabolically-derived carbon present in shark and ray ageing structures. 

### Magnitude and manifestation 
The mean magnitude of age underestimation, $\Delta_{Mean}$, detected using bomb carbon dating ranged from `r DeltaMeanRange[1]%>%n2w` years in thorny skates (*Leucoraja ocellata*, Rajidae) [@mcphie_bomb_2009], to `r DeltaMeanRange[2]` years in New Zealand porbeagle sharks [@francis_age_2007], averaging `r DeltaMeanMean` years across all studies (Table 2). The greatest individual disparity between true and apparent age, $\Delta_{Max}$, was also in a New Zealand porbeagle shark that was underaged by `r DeltaMaxRange[2]` years. However, this population appeared to be exceptional and the next largest disparity was in a northwest Atlantic white shark underaged by `r rev(sort(data1$Magnitude.max))[2]` years [@hamady_vertebral_2014]. $\Delta_{Max}$ averaged `r DeltaMaxMean` years across all studies. For chemically marked populations the estimation of $\Delta_{Mean}$ and $\Delta_{Max}$ was limited by the short duration of studies and small sample sizes; both ranged from 2 to 3 years. 

Among the `r Underestimate[1,1]` bomb carbon dating studies where age underestimation was likely, `r nrow(dataIND)` individual samples were pooled for analysis. With the exception of three outliers (two northeast Pacific white sharks and one school shark), there were consistent patterns in the relative lengths and ages that it occurred in (Fig. 3a). Relative length, in particular, was a strong and highly significant predictor of occurrence (Likelihood ratio test: $\chi^2$=`r round(anova(m1,test="Chisq")$Deviance[2],2)`, *d.f.*=1, *P*<0.01). At lengths above `r round(MASS::dose.p(m1)[1],2)*100`% of $L_\infty$ more than half of all individuals were underaged (Fig. 3b, Table 3). Relative age was also a highly significant predictor of occurrence (Likelihood ratio test: $\chi^2$=`r round(anova(m2,test="Chisq")$Deviance[2],2)`, *d.f.*=1, *P*<0.01). At ages above `r round(MASS::dose.p(m2)[1],2)*100`% of $A_{Max}$ more than half of individuals were underaged (Fig. 3c, Table 3). This implies that, on average, ageing structures provided a valid record of age for less than half of the maximum longevity of the species. 

Using the definitions in Table 1, the extent of age underestimation in bomb carbon dating studies is even more pronounced, since any ages above the age that it is first detected are effectively uncertain. Based on these definitions, growth zones were a reliable and valid indicator of true age for approximately a third of total lifespan (median = `r Prop.valid$Prop.valid %>% median`%) (Fig. 1, Table 2).

### How pervasive is age underestimation?
Determining just how pervasive age underestimation is in sharks and rays is difficult since chemical marking seems inherently less likely to detect it than bomb carbon dating. It is also possible that both methods may be unable to detect it or decouple it from other processes in certain situations. Shark and ray age validation studies in general were characterized by very low sample sizes -- `r (100*(table(data1$n<10)[2]/ length(data1$n)))%>%round(0)`% of studies were based on fewer than 10 samples, and  `r (100*(table(data1$n<2)[2]/length(data1$n)))%>%round(0)`% were based on only a single individual (Fig. 1, Fig. 2). The relatively high frequency of detection in spite of these small sample sizes suggests it must be relatively common. 

Age underestimation occurred in at least `r UnderestimateGenus%>%n2w` different genera (Table 2), indicating it is a widespread phenomenon. Although predominantly detected in two orders, the Lamniformes and Carcharhiniformes, these were also by far the most intensively studied (see Supplementary Material). Age underestimation does not seem to be restricted to particular life history types, and has been reported in some relatively small and short-lived species such as blue-spotted mask rays (*Neotrygon kuhlii*, Dasyatidae) [@pierce_validated_2009] as well as large and long-lived species such as dusky sharks (*Carcharhinus obscurus*, Carcharhinidae) [@natanson_validated_2014].  

Although common and widespread, it does not seem to be ubiquitous, and was absent from some well-studied species. Age underestimation has not been reported in gummy sharks (*Mustelus antarcticus*, Triakidae) a species studied concurrently with school sharks over many decades in southern Australian waters [@walker_age_2001]. Likewise, there is no evidence for it in the well-studied leopard shark (*Triakis semifasciata*, Triakidae) (although Kusher *et al.* [-@kusher_validated_1992] noted that OTC uptake was insufficient for age validation in 65% of recaptured sharks). There is also evidence of intraspecific variability in its occurrence; it was absent in northwest Atlantic porbeagle sharks [@campana_bomb_2002] but present in New Zealand porbeagles [@francis_age_2007] (differences in sampling and exploitation history [@cassoff_changes_2007] should be noted here, however). 

Two interrelated and mutually inclusive hypotheses have been proposed to explain age underestimation in shark and ray ageing studies:

1) it results from growth zones becoming vanishingly small and unresolvable on the margin of ageing structures as individuals get larger and older, and as growth decreases [@francis_age_2007; @chin_validated_2013; @hamady_vertebral_2014], or 

2) it results from a temporary or permanent cessation of growth and growth zone formation [@natanson_validated_2014] potentially occurring at any life stage, including in response to a reallocation of resources to reproduction [@natanson_effect_1993; @harry_age_2013] or from "feast and famine" feeding behavior [@andrews_validated_2015]. 

Current evidence does not clearly favor either hypothesis. On the one hand, age determination in many sharks and rays is inherently difficult, and progress in ageing slow due in large part to the limitations of available ageing structures [@cailliet_age_2004; @goldman_assessing_2012]. Intraspecifically, counts and readability of growth zones have been shown to vary depending on the method of preparation [@irvine_surface_2006], reader experience [@officer_sources_1996], type of structure used [@bubley_reassessment_2012], and region of the vertebral column sampled [@natanson_age_2015]. The hypothesis that growth zones simply become unresolvable is appealing since it implies that, with the right method of preparation, the true age may still be attainable. However, it also risks overlooking the extensive research done with the aim of enhancing the readability of ageing structures. This includes histology [@natanson_effect_1993], radiography [@aasen_length_1963], scanning x-ray fluorescence microscopy [@raoult_strontium_2016], micro-computed tomography [@geraghty_micro-computed_2012] and a multitude of staining and sectioning techniques [@cailliet_techniques_1983; @goldman_assessing_2012]. While these techniques have sometimes revealed underageing [@maurer_life_2009; @francis_age_2007], none has yet indicated that counts may be underestimated by the large magnitudes documented here.

On the other hand, the hypothesis that age underestimation is due to growth zones ceasing to form also has foundation. Otolith mineralization differs from most other calcified structures found in vertebrates, taking place within an acellular medium known as endolymph with deposition of new material occurring daily [@morales-nin_review_2000; @payan_endolymph_2004]. Francis *et al.* [-@francis_age_2007] note that "vertebrae form part of the axial skeleton of a shark so, in theory, if the shark's somatic growth ceases, then deposition of material on the outer margin of the vertebrae should also cease". Elasmobranch vertebral centra, the structures used most commonly for age determination, are a form of densely calcified 'areolar' cartilage found uniquely within the vertebrae [@dean_mineralized_2006]. Unlike bone, mineral content in shark and ray cartilage has been shown to vary within individuals, intraspecifically, and interspecifically [@porter_contribution_2007]. Indeed, the vertebral centra of sharks and rays are so variable that they were initially thought to be useful for taxonomic classification [@ridewood_calcification_1921]. In addition to this, the physiological and mechanical factors that mediate mineralization of vertebrae are still largely unknown [@dean_mineralized_2006; @porter_contribution_2007], despite long being recognized as centrally important to ageing [@cailliet_elasmobranch_1986]. So while counts of growth zones obtained from shark and ray ageing structures are essentially treated the same as those from otoliths, the underlying processes that generate them have not been demonstrated to be the same, and may well differ.

Evidence from bomb carbon dating, where age underestimation manifested almost entirely in larger and older individuals, is consistent with the suggestion that growth zone periodicity changes or ceases later in life, potentially after the onset of sexual maturity [@casey_revised_1992; @natanson_analysis_2016]. While no conclusive link with maturation has been demonstrated, this would provide a physiological mechanism to explain age underestimation. Growth zone formation has also recently been shown to shift from biannual to annual after maturity in shortfin mako vertebrae [@kinney_oxytetracycline_2016]. Many sharks and rays have reproductive cycles that last two or more years, so if the timing and frequency of growth zones are linked to reproductive events, associated changes in the frequency of growth zone formation could be difficult to detect, and may only gradually become evident after several full reproductive cycles. 

At present little can be definitively said about the mechanisms underlying age underestimation. In summary though, it appears to be common and widespread and manifests in similar ways across a range of species. On the balance of this evidence, it seems likely to be a systemic issue associated with the current methods and structures used for ageing sharks and rays. While it may not occur in all species, it will probably continue to be detected as validation studies increase and expand across taxa, particularly if ageing methods remain unchanged. 

### Implications
The findings of this study are relevant to the numerous species that have been and continue to be aged by counting growth zones on calcified structures. Importantly, this study confirms that it is no longer sufficient to assume growth zones are deposited regularly on ageing structures throughout life, reinforcing the need for ongoing validation of all age classes. Yet while numerous studies have now documented age underestimation, there has still been no directed investigation of its effects and only limited discussion of its possible implications. As a starting point I consider the potential effects in relation to two fundamental population processes, growth and mortality.

#### Growth
One of the most clearly apparent effects of underestimating age relates to modelling growth. Since ages from growth zone counts are an unknown function of true age, it follows that any growth parameters estimated from these data are likely to be biased. Francis *et al.* [-@francis_age_2007], the only authors to so far correct for age underestimation, used a modified Von Bertalanffy growth function to adjust growth zone counts to reflect true ages. Natanson *et al.* [-@natanson_analysis_2016] on the other hand, opted to remove all ages deemed unreliable (> 14 years) and used only back-calculated data when re-fitting growth curves to account for age underestimation in common thresher sharks (*Alopias vulpinus*, Alopiidae). In both these particular cases the resultant growth curves were similar to those fit to the original data, suggesting that any bias was minimal. Indeed, this may be expected since age was underestimated in individuals that had completed most of their growth already. 

Simulating data from the models in Francis *et al.* [-@francis_age_2007] suggests that age underestimation could still have a pronounced impact, especially when sample sizes are small. Through the underestimation of age, there is an apparent 'loss' of older individuals from length-at-age data. This effectively truncates the asymptote of the growth curve, presumably making it more difficult to obtain an unbiased estimate of $L_\infty$ (Fig. 4a). $L_\infty$ is strongly, negatively correlated with the growth coefficient, *k*, in many commonly used models for describing fish growth. As such, a positively biased (larger) $L_\infty$ associated with this apparent absence of older individuals would lead to a negatively biased (lower) *k*, somewhat analogous to the bias generated by length-selective fishing gears such as gillnets [@walker_phenomenon_1998; @thorson_gear_2009]. This phenomenon was seen in northwest Atlantic dusky sharks; using validated data points corrected for age underestimation led to an increase in the estimated growth coefficient of 6-17% and a decrease in $L_\infty$ of 8-9% [@natanson_validated_2014]. Growth coefficients, *k*, estimated from vertebral ageing of school sharks, where ages are known to be substantially underestimated, were 24-26% lower than estimated from two long-term tagging studies [@moulton_age_1992]. Thus, a paradox of underestimating age is that the bias introduced may lead to an underestimate of the growth coefficient, not an overestimate, as would be intuitively expected. 

Francis *et al.* [-@francis_age_2007] showed that simple corrections can account for some of the bias associated with age underestimation. However, under even slightly more complex assumptions it is clear that additional biases would be more difficult to correct for. For example, assuming that the growth coefficient (i.e. *k*) varies among individuals in a population and that age underestimation is predominantly a function of length, it would be expected to disproportionately impact faster growing individuals (Fig. 4b). At the very least it is likely to further add to the challenge of estimating robust growth parameters in sharks and rays by compounding biases caused by length selective fishing, low sample sizes, and growth model uncertainty. 

#### Mortality
The more directly obvious impact of age underestimation is on longevity. The frequency and magnitude of age underestimation documented here indicates that many sharks and rays are likely to live much longer than currently thought. This is important since longevity is frequently used to make inferences about natural mortality, *M*, a parameter that is highly influential in population models and that nearly always has to be pre-specified for information-limited taxa such as sharks and rays [@kenchington_natural_2014]. Reduced longevity is also symptomatic of a more general 'loss of age structure' caused by age underestimation, which presents a potentially more serious issue than biased growth parameters. When using age structured population models that are fit to these data such as catch curves [@simpfendorfer_mortality_1999; @robbins_ongoing_2006], this apparent loss of population age structure could be inadvertently attributed to or indistinguishable from fishing mortality (Fig. 4c). 

Understanding the impacts of these biases on populations, which are influenced by complex and non-linear dynamics, is not straightforward. Shorter-lived species are generally more productive (i.e. have a higher recruitment). The much greater longevity found for many species may indicate they have a lower natural mortality and in turn lower productivity and resilience to fishing than currently thought. In contrast, in a simple demographic analysis assuming Hoenig mortality for New Zealand porbeagles, use of the true longevity of 65 years results in a much greater net reproductive rate, $R_0$, than if the apparent longevity of 38 years is used. This translates to a population doubling time of ~9 years compared with ~22 years (Fig. 4d), implying much greater population productivity. In sand tiger sharks (*Carcharias taurus*, Odontaspididae) it was noted that the upward revision of lifespan to 40 years would lead to at least five times more reproductive years than previously thought, again implying increased productivity [@passerotti_maximum_2014]. 

\begin{center}
\noindent\rule{2cm}{0.4pt}
\end{center}

These examples, while simplistic, highlight the potential ways that age underestimation may have skewed understanding of shark and ray population dynamics. With only a handful of long-term, empirical observations of wild shark and ray populations (e.g. Feldheim *et al.* [-@feldheim_two_2014]), current perceptions of population dynamics, including key areas such as fisheries productivity reference points and extinction risk, are strongly shaped by comparative life history studies [@cortes_life_2000; @frisk_estimation_2001; @frisk_life_2005; @pardo_maximum_2016] and meta-analyses [@garcia_importance_2008; @hutchings_life-history_2012; @zhou_linking_2012] that draw heavily upon age and growth studies.

Such are the data limitations for many populations that assessments are often based solely on life history information [@cortes_incorporating_2002; @brooks_analytical_2009; @cortes_perspectives_2016]. This means that the above issues have the potential to extend well beyond the specific examples above. For example, age-at-maturity, another key determinant of population productivity [@smith_intrinsic_1998; @pardo_maximum_2016], is frequently obtained from the inverse of a growth curve at length-at-maturity, meaning it too would be susceptible to biased growth parameters. Sidestepping the use of biased parameters altogether is also difficult. While it may be possible to use assessment techniques that avoid specifying, say, longevity [@xiao_relationship_2002; @skalski_effects_2008], it is generally not possible to avoid *M* altogether. Furthermore, almost all life history invariant techniques that are used to pre-specify *M* require the use of length-at-age, growth parameters, or longevity [@kenchington_natural_2014; @then_evaluating_2014]. These dependencies mean there is considerable potential for ageing error to propagate through population assessments.

Through these types of biases, age underestimation may have important flow-on effects for fisheries management and conservation. With age-structured population models increasingly being used to support management of commercially exploited stocks [@cortes_population_2012], model misspecficiation due to ageing error has the potential to affect scientific advice such as acceptable catch limits. The impacts that these types of errors can have are well documented in teleosts [@yule_how_2008; @melvin_high_2010]. For example, underestimation of longevity in orange roughy (*Hoplostethus atlanticus*, Trachichthyidae) [@smith_age_1995] and Pacific ocean perch (*Sebastes alutus*, Sebastidae) [@beamish_new_1979] led to overly optimistic estimates of stock productivity, in both cases contributing to serious, long-term ecological and socio-economic impacts on these resources. 

Given that sharks and rays are often not the target of fishing activities, management strategies are typically less responsive. They are often centered around the identification and protection of high-risk species or mitigation of high-risk activities using measures such as spatial and temporal closures and species catch restrictions. Because of this, the ultimate impacts of age underestimation from a conservation or fisheries management perspective may well be more insidious, occurring through the misclassification of high-risk species, leading to inefficient prioritization of research, monitoring, and management measures. If age underestimation is indeed as widespread and common as indicated from this study, the impacts could also be substantial from a wider scientific perspective, affecting the many disciplines that also use baseline life history data. 

The implications of age underestimation are also by no means restricted to sharks and rays, and this study serves as a reminder of the potential impacts on fish more generally. While the processes governing otolith mineralization are well understood, many species, particularly long-lived and deep-water, are nonetheless difficult to age, which can lead to underestimation of true age. Similar phase-shifts to those reviewed here have been documented in bocaccio rockfish (*Sebastes paucispinis*, Sebastidae) [@andrews_bomb_2005], for example. The use of whole rather than sectioned otoliths has also frequently been shown to underestimate age [@bennett_confirmation_1982; @dwyer_age_2016]. For example, the use of whole otoliths likely resulted in a biased growth curve for southern bluefin tuna (*Thunnus maccoyii*, Scombridae) [@gunn_age_2008]. In addition to this, a range of structures other than otoliths are routinely used to age fish, many of which have been shown to underestimate age including scales [@secor_validation_1995], fin-rays [@rien_accuracy_1994], and vertebrae [@gunn_age_2008]. In most of these instances, the impacts of ageing error are presumably isolated to specific populations. Nonetheless, for groups of species that are difficult to or unable to be aged using otoliths, the potential exists for more widespread biases to manifest.

### Confronting the challenges of shark and ray ageing
The outcomes of this study highlight the ongoing difficulties of ageing sharks and rays using calcified structures, particularly the validation of growth zones in older individuals. At present it is unclear whether the underestimation of ages is a major problem, or perhaps a simple bias that, for some applications, could be corrected with adjustments like those made to otolith back-calculations [@campana_how_1990] or worn spines [@taylor_spine-based_2013]. Although this study is the first time data have been synthesized and quantified on age underestimation, the issue is far from new [@kalish_determination_2001]. But despite repeated invalidation of ageing structures in older individuals of a range of species, it has not yet led to widespread changes to ageing practices or growth modeling. 

Understanding the extent of the problem and ultimately addressing it will require, in the first instance, more data. While the number of age validation studies has increased in recent years, the studies reviewed here cover fewer than 5% of described species (Fig. 1 and Fig. 2). As noted by Cailliet [-@cailliet_perspectives_2015] and emphasized by Figure 2, even fewer of these species have been validated convincingly. Bomb carbon dating appears to be the most effective tool currently available for age validation of sharks and rays; it is the most likely to give a true indication of longevity and detect whether age has been underestimated. The high cost of such studies, the increasing difficulty of obtaining archived samples born prior to the rise in $\Delta^{14}\textup{C}$, and the unsuitability for shorter-lived species mean it is not a 'silver bullet'. 

Fluorochrome chemical marking is clearly an effective tool in some situations, however this study raises questions about its usefulness for validating older age-classes and why it seemingly fails in many cases. The ongoing use of chemical markers in laboratory-based studies to quantify mineralization rates may help resolve some of these questions [@officer_captive_1997], particularly if they can be extended to examine the influence of factors such as length, age, and maturity stage. Extending the inferences from these studies to wild populations is always problematic, and therefore long-term tag-recapture studies targeting both juveniles and adults are the only way to convincingly validate age and the efficacy of chemical marking in older individuals. As this study shows, the costs and logistical difficulties of conducting either type of study have so far made them feasible for a very small number of stocks globally, and this seems unlikely to change in the foreseeable future. 

As the enormity and complexity of the conservation challenges facing sharks and rays globally becomes increasingly clear [@dulvy_extinction_2014; @dulvy_challenges_2017], there may be a need to confront the wider issue, that calcified structures may be insufficient to meet the ageing needs of many species. While there are many excellent examples that illustrate that sharks and rays can be aged successfully using calcified structures, after more than 50 years of ageing, one of the most consistent feature of such structures is their inconsistency [@goldman_assessing_2012; @cailliet_perspectives_2015]. With no foreseeable end to the difficulties associated with traditional ageing structures, it may be time to look for solutions that complement existing methods and can assist in building the deeper understanding of growth and mortality needed for effective conservation and management. 

One such solution could include a shift in focus toward the use of alternative data sources, for example tag-recapture and length-based data for estimating growth. Although commonly used, there has been a tendency to view these data as less credible compared to those derived from calcified ageing structures which, until now, have been seen as the more reliable source of information. Indeed, many of the studies reviewed here also included tag-recapture components that were often discussed in less detail and rarely considered the 'preferred' growth model [@davenport_age_1988; @mcauley_validated_2006; @kneebone_using_2008; @andrews_bomb_2011]. Comparison of growth parameters derived from populations studied simultaneous using both methods may also be one of the only ways to empirically determine whether some of the expected biases proposed here really exist.

In recent years, tagging programs for sharks and rays have increasingly been initiated for various non-fishery related applications (e.g. acoustic telemetry, ecological study, human-safety) and by non-fisheries institutions (e.g. universities, ENGOs). Such programs can potentially be of considerable value in supplementing the limited resources of fisheries agencies for obtaining long-term data on growth. The use of tagging and length-based methods is also consistent with the shift towards non-lethal alternatives to sampling that are now increasingly being advocated [@hammerschlag_killing_2011]. Opportunities for collecting and making tag-recapture data publicly available for age and growth estimation purposes should be embraced where possible. 

## Conclusions

> *The prevalence and impact of inaccurate age determinations on the accuracy of population dynamics studies cannot be overstated* [@campana_accuracy_2001]

The study of shark and ray life history has evolved in much the same way as in teleost fish. It is, in large part, built upon the ageing of individuals from which parameters such as growth, age at maturity, longevity, and mortality are estimated or indirectly inferred. The simple assumption underpinning this process is that counts of growth zones do indeed provide a valid record of age throughout life. The comprehensive review of bomb carbon dating and chemical marking age validation studies undertaken here shows that this assumption is frequently violated, highlighting a systemic problem associated with the most common method and structures used for ageing. Given the inherent difficulties in studying wild populations, age and growth studies form the basis of much of the current understanding of shark and ray population dynamics. So while age underestimation, in isolation, may be regarded as a relatively unimportant or minor issue, its impacts could still be far reaching and warrant closer attention. The ongoing potential for it to compound the existing, significant challenges in obtaining accurate estimates of growth, longevity, and mortality for sharks and rays should not be overlooked.

## Acknowledgements
This manuscript benefited greatly from detailed and insightful reviews by L. J. Natanson, E. Cort$\acute{\textup{e}}$s, and a third, anonymous reviewer. Thank you to D. S. Waltrick and L. F. N. Waltrick for your support and encouragement. 

\newpage
## References